FROM python:2.7-slim

RUN set -x \
	&& buildDeps=' \
		curl \
		g++ \
		gcc \
		libbz2-dev \
		libc6-dev \
		libffi-dev \
		libmysqld-dev \
		libncurses-dev \
		libreadline-dev \
		libsqlite3-dev \
		libssl-dev \
		libxml2-dev \
		libxslt-dev \
		libblas-dev \
		liblapack-dev \
		libatlas-base-dev \
		gfortran \
		make \
		supervisor \
		xz-utils \
		zlib1g-dev \
	' \
	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir virtualenv
RUN pip install 'MySQL-python<=1.2.3' \
	&& pip install Celery \
	&& pip install leancloud-sdk \
	&& pip install qingcloud-sdk \
	&& pip install mysql \
	&& pip install numexpr \
	&& pip install numpy \
	&& pip install pandas \
	&& pip install pyopenssl \
	&& pip install pymongo \
	&& pip install redis \
	&& pip install SciPy \
	&& pip install scikit-learn \
	&& pip install Scrapy \
	&& pip install scrapy_redis \
	&& pip install sqlalchemy \
	&& pip install twisted \
	&& pip install xlsxwriter \
	&& pip install lxml

VOLUME ["/opt/python/app"]
WORKDIR /opt/python/app
ENTRYPOINT ["python2"]
